// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $bluesky from "./routes/bluesky.tsx"
import * as $fr_index from "./routes/fr/index.tsx"
import * as $greet_name_ from "./routes/greet/[name].tsx"
import * as $index from "./routes/index.tsx"
import * as $parti_party_ from "./routes/parti/[party].tsx"
import * as $Counter from "./islands/Counter.tsx"
import * as $OpenBlueskyTabs from "./islands/OpenBlueskyTabs.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/bluesky.tsx": $bluesky,
    "./routes/fr/index.tsx": $fr_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/parti/[party].tsx": $parti_party_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/OpenBlueskyTabs.tsx": $OpenBlueskyTabs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
